name: prod workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # - name: SonarQube Scan
      # uses: sijomc/sonarscan-action@1.1
      # with:
        # host: ${{ secrets.SONARQUBE_HOST }}
        # login: ${{ secrets.SONARQUBE_LOGIN }}
        # projectKey: ${{ secrets.SONAR_PROJECT_KEY }}
        # projectName: ${{ secrets.SONAR_PROJECT_KEY}}

    - name: docker login
      env: 
        DOCKER_USER: ${{secrets.DOCKER_USERNAME_PROD}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD_PROD}}
      run: |
           docker login -u $DOCKER_USER -p $DOCKER_PASSWORD easyprod.azurecr.io        
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag easyprod.azurecr.io/radical-swagger-documentation-server:latest
    - name:  Docker push
      run: docker push easyprod.azurecr.io/radical-swagger-documentation-server:latest

    ####### Deploy to K8s Cluster #######
    - name: Azure Kubernetes set context
      uses: azure/k8s-set-context@v1
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.PROD_KUBE_CONFIG }}
        context: ap-prod
      id: login

      # Deploy to k8s cluster
    - name: Deploy to Kubernetes cluster
      uses: Azure/k8s-deploy@v1.4
      with:
        manifests: |
          k8s/prod/deployment.yaml
          k8s/prod/configmap.yaml
          k8s/prod/ingress.yaml
          k8s/prod/service.yaml
        images: 'easyprod.azurecr.io/radical-swagger-documentation-server:latest'
        imagepullsecrets: easycoop-prod
        namespace: easycoop
        action: deploy

    # restart pods
    - run: |
        kubectl -n easycoop rollout restart deployment radical-swagger-documentation-server